import { useEffect, useState } from 'react'
import { BookOpen, ClipboardList, Plus, UserPlus, Users } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import Modal from '../components/Modal.jsx'
import StatCard from '../components/StatCard.jsx'
import DashboardLayout from '../layouts/DashboardLayout.jsx'
import { api, normalizeCourses } from '../api/client.js'

export default function AdminDashboard() {
  const navigate = useNavigate()
  const [report, setReport] = useState(null)
  const [modal, setModal] = useState(null)
  const [message, setMessage] = useState('Cargando panel administrativo...')
  const [data, setData] = useState(null)
  async function load(){ const res = await api('/api/admin/dashboard'); setData({...res, cursos: normalizeCourses(res.cursos || [])}); setMessage('Panel administrativo actualizado') }
  useEffect(()=>{ load().catch(e=>setMessage(e.message)) }, [])
  const users = data?.usuarios || []
  const courses = data?.cursos || []
  const enrollments = data?.inscripciones || []
  async function saveUser(e){ e.preventDefault(); const f=new FormData(e.currentTarget); await api('/api/admin/usuarios',{method:'POST',body:JSON.stringify({nombres:f.get('nombres'),apellidos:f.get('apellidos'),correo:f.get('correo'),password:f.get('password'),rol:f.get('rol'),especialidad:f.get('especialidad')})}); setMessage('Usuario creado correctamente'); setModal(null); await load() }
  async function saveCourse(e){ e.preventDefault(); const f=new FormData(e.currentTarget); await api('/api/admin/cursos',{method:'POST',body:JSON.stringify({codigo:f.get('codigo'),nombre:f.get('nombre'),descripcion:f.get('descripcion'),creditos:Number(f.get('creditos')),ciclo:'2026-1',modalidad:f.get('modalidad'),categoria:f.get('categoria'),estado:'Activo',avance:0,color:'blue',aula:f.get('aula'),horario:f.get('horario'),docenteId:Number(f.get('docenteId')),estudianteIds:f.getAll('estudianteIds').map(Number)})}); setMessage('Curso creado correctamente'); setModal(null); await load() }
  const docentes = users.filter(u=>u.rol==='DOCENTE')
  const estudiantes = users.filter(u=>u.rol==='ESTUDIANTE')
  return <DashboardLayout role="ADMIN" title="Panel administrador" subtitle="Gestion general del sistema academico">
    <section className="grid sm:grid-cols-2 xl:grid-cols-4 gap-5 mb-8"><StatCard icon={Users} label="Usuarios" value={data?.totalUsuarios || users.length} detail="Admin, docentes y estudiantes" /><StatCard icon={BookOpen} label="Cursos" value={data?.totalCursos || courses.length} tone="green" /><StatCard icon={ClipboardList} label="Inscripciones" value={data?.totalInscripciones || enrollments.length} tone="purple" /><StatCard icon={UserPlus} label="Actividades" value={data?.totalActividades || 0} tone="orange" /></section>
    <div className="rounded-3xl bg-white border border-slate-100 p-5 shadow-card mb-8 flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div><h3 className="font-black text-slate-900">Gestion administrativa</h3><p className="text-sm text-slate-500 mt-1">{message}</p></div><div className="flex flex-col sm:flex-row gap-3"><button onClick={() => setModal('usuario')} className="rounded-2xl bg-blue-600 px-5 py-3 text-white font-black hover:bg-blue-700 transition flex items-center justify-center gap-2"><Plus size={18}/>Crear usuario</button><button onClick={() => setModal('curso')} className="rounded-2xl bg-slate-900 px-5 py-3 text-white font-black hover:bg-blue-700 transition flex items-center justify-center gap-2"><Plus size={18}/>Crear curso</button></div></div>
    <div className="grid xl:grid-cols-2 gap-7"><Table title="Usuarios registrados" headers={['Nombre','Correo','Rol','Estado']} rows={users.map(u => [`${u.nombres} ${u.apellidos}`, u.correo, u.rol, u.estado])} /><Table title="Cursos publicados" headers={['Curso','Docente','Modalidad','Creditos']} rows={courses.map(c => [c.nombre, c.docente, c.modalidad, c.creditos])} /><Table title="Inscripciones" headers={['Estudiante','Curso','Estado']} rows={enrollments.map(i => [`${i.estudiante?.nombres || ''} ${i.estudiante?.apellidos || ''}`, i.curso?.nombre || '', i.estado])} /><div className="rounded-3xl bg-white border border-slate-100 p-6 shadow-card"><h3 className="font-black text-slate-900 mb-4">Reportes rapidos</h3>{['Reporte de estudiantes', 'Reporte de docentes', 'Reporte de cursos', 'Reporte de inscripciones'].map(r => <button key={r} onClick={() => setReport(r)} className="w-full mb-3 rounded-2xl bg-slate-50 border border-slate-100 px-4 py-4 text-left font-black text-slate-700 hover:bg-blue-50 hover:text-blue-700 transition">{r}</button>)}<button onClick={() => navigate('/admin/reportes')} className="w-full rounded-2xl bg-blue-600 text-white px-4 py-4 text-left font-black hover:bg-blue-700 transition">Abrir modulo de reportes</button></div></div>
    {report && <Modal title={report} onClose={() => setReport(null)}><div className="space-y-4"><p className="text-slate-600">Vista previa generada con la informacion registrada en el sistema.</p><div className="rounded-2xl bg-slate-50 border border-slate-100 p-4"><p className="font-black text-slate-900">Resumen</p><p className="text-sm text-slate-500 mt-1">Usuarios: {users.length} | Cursos: {courses.length} | Inscripciones: {enrollments.length}</p></div><button onClick={() => navigate('/admin/reportes')} className="w-full rounded-2xl bg-blue-600 py-3.5 text-white font-black">Ver reporte completo</button></div></Modal>}
    {modal === 'usuario' && <Modal title="Crear usuario" onClose={() => setModal(null)}><form onSubmit={saveUser} className="grid sm:grid-cols-2 gap-4"><Input name="nombres" label="Nombres"/><Input name="apellidos" label="Apellidos"/><Input name="correo" label="Correo" type="email"/><Input name="password" label="Contrasena" type="password"/><Input name="especialidad" label="Especialidad"/><label className="block"><span className="text-sm font-black text-slate-700">Rol</span><select name="rol" className="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3"><option>ADMIN</option><option>DOCENTE</option><option>ESTUDIANTE</option></select></label><button className="sm:col-span-2 rounded-2xl bg-blue-600 py-3.5 text-white font-black">Guardar usuario</button></form></Modal>}
    {modal === 'curso' && <Modal title="Crear curso" onClose={() => setModal(null)}><form onSubmit={saveCourse} className="grid sm:grid-cols-2 gap-4"><Input name="nombre" label="Nombre del curso"/><Input name="codigo" label="Codigo"/><Input name="creditos" label="Creditos" type="number"/><Input name="categoria" label="Categoria"/><Input name="aula" label="Aula o laboratorio"/><Input name="horario" label="Horario"/><label className="block"><span className="text-sm font-black text-slate-700">Modalidad</span><select name="modalidad" className="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3"><option>Virtual 24/7</option><option>Virtual</option><option>Presencial</option></select></label><label className="block"><span className="text-sm font-black text-slate-700">Docente</span><select name="docenteId" className="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3">{docentes.map(d=><option key={d.id} value={d.id}>{d.nombres} {d.apellidos}</option>)}</select></label><label className="block sm:col-span-2"><span className="text-sm font-black text-slate-700">Matricular estudiantes</span><select name="estudianteIds" multiple className="mt-2 w-full min-h-28 rounded-2xl border border-slate-200 px-4 py-3">{estudiantes.map(e=><option key={e.id} value={e.id}>{e.nombres} {e.apellidos} - {e.correo}</option>)}</select><p className="mt-2 text-xs text-slate-500 font-bold">Ctrl + clic para seleccionar varios.</p></label><label className="block sm:col-span-2"><span className="text-sm font-black text-slate-700">Descripcion</span><textarea name="descripcion" required rows="4" className="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3" /></label><button className="sm:col-span-2 rounded-2xl bg-blue-600 py-3.5 text-white font-black">Guardar curso y matricular</button></form></Modal>}
  </DashboardLayout>
}
function Table({ title, headers, rows }) { return <div className="rounded-3xl bg-white border border-slate-100 p-6 shadow-card overflow-hidden"><h3 className="font-black text-slate-900 mb-4">{title}</h3><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{headers.map(h => <th key={h} className="text-left py-3 px-3 bg-slate-50 text-slate-500 font-black first:rounded-l-xl last:rounded-r-xl">{h}</th>)}</tr></thead><tbody>{rows.map((r,i) => <tr key={i} className="border-b border-slate-100 last:border-0">{r.map((c,j) => <td key={j} className="py-4 px-3 font-semibold text-slate-700">{c}</td>)}</tr>)}</tbody></table></div></div> }
function Input({ label, name, type='text' }) { return <label className="block"><span className="text-sm font-black text-slate-700">{label}</span><input name={name} type={type} required className="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:ring-4 focus:ring-blue-100" /></label> }
